### PR TITLE
Bump Alpine to 3.19 and switch to openresty 0.0.2 to prefix the package name

### PR DESCRIPTION
**Pull request by jandubois**

### CODE REVIEW

**Review by mook-as — APPROVED** [review]
Looks like https://github.com/rancher-sandbox/openresty-packaging/commit/9599e12db1d71faad6a0d423bbc3b034df2184e0 is the relevant fix.

**Review by mook-as — CHANGES_REQUESTED** [review]
Jan says there are issues with k3s and cgroupsv2. We shouldn't merge this until we can sort that out (to avoid issues with accidentally bumping this in RD and then making a release blocker).

**Comment by jandubois** [comment]
> Jan says there are issues with k3s and cgroupsv2.

That was with Alpine 3.19 on Lima (macOS); I haven't tested it on Windows yet, where this might be controlled by WSL2 instead.

> We shouldn't merge this until

Yes, will turn into draft for now.

**Comment by jandubois** [comment]
I think this PR is ready for review/merging now. It passes [E2E tests on Windows] (https://github.com/rancher-sandbox/rancher-desktop/actions/runs/7702707188/job/20991555355?pr=6373) and continues to support `k3d` as before:

```console
C:\Users\SUSE\AppData\Local\rancher-desktop\logs>k3d cluster create
INFO[0000] Prep: Network
INFO[0000] Created network 'k3d-k3s-default'
INFO[0000] Created image volume k3d-k3s-default-images
INFO[0000] Starting new tools node...
INFO[0001] Creating node 'k3d-k3s-default-server-0'
INFO[0012] Pulling image 'docker.io/rancher/k3s:v1.27.4-k3s1'
INFO[0015] Pulling image 'ghcr.io/k3d-io/k3d-tools:5.6.0'
INFO[0024] Creating LoadBalancer 'k3d-k3s-default-serverlb'
INFO[0024] Starting Node 'k3d-k3s-default-tools'
INFO[0039] Pulling image 'ghcr.io/k3d-io/k3d-proxy:5.6.0'
INFO[0063] Using the k3d-tools node to gather environment information
INFO[0063] HostIP: using network gateway 172.19.0.1 address
INFO[0063] Starting cluster 'k3s-default'
INFO[0063] Starting servers...
INFO[0063] Starting Node 'k3d-k3s-default-server-0'
INFO[0068] All agents already running.
                                                        INFO[0068] Starting helpers...
                                                                                                                INFO[0069] Starting Node 'k3d-k3s-default-serverlb'
                                                INFO[0075] Injecting records for hostAliases (incl. host.k3d.internal) and for 2 network members into CoreDNS configmap...
                                                   INFO[0077] Cluster 'k3s-default' created successfully!
                                                                                                           INFO[0077] You can now use it like this:
                                           kubectl cluster-info

C:\Users\SUSE\AppData\Local\rancher-desktop\logs>kubectl get no
NAME                       STATUS   ROLES                  AGE   VERSION
k3d-k3s-default-server-0   Ready    control-plane,master   18s   v1.27.4+k3s1
```

(yes, the wonky formatting of the latter log lines looked like this in the terminal too)

**Review by mook-as — APPROVED** [review]
We still do [`rc_cgroup_mode=none`](https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/blob/9b59b499d68e9f75c18be958b2aa9a9c111172c8/files/build.sh#L23) because WSL manages cgroups (it's a kernel thing, and not namespaced in a way that lets us manage v1/v2).

**Pull request merged**
